### PR TITLE
Update EnforcedStyleAlignWith to keyword in Layout/EndAlignment

### PR DESCRIPTION
**Pull request by brunto**
With the current configuration `EnforcedStyleAlignWith: variable`, the result is:

```
data = if true
  'true'
else
  'false'
end
```

With `EnforcedStyleAlignWith: keyword`  the result looks better:

```
data = if true
         'true'
       else
         'false'
       end
```

### CODE REVIEW

**Comment by brunoprietog** [comment]
From readme:

> These omakase styles are not intended as an invitation to bikeshed code style preferences. If you disagree with some of the rules incorporated here, you should specialize them in your own application. If you disagree with most of the rules, you should just create your own style guide from scratch.

**Comment by brunto** [comment]
Yes, I read this. My opinion is that nobody uses `EnforcedStyleAlignWith: variable` but maybe I'm wrong.

**Comment by koic** [comment]
FYI, As an example of a style setting that differs from rubocop-rails-omakase, rails/rails repo adopts `EnforcedStyleAlignWith: variable`.
https://github.com/rails/rails/blob/v7.1.2/.rubocop.yml#L77-L80

**Comment by brunto** [comment]
OK I understand. I'm going to overwrite it in my configuration.

**Pull request closed without merging**
